import { IRndExpert } from "../../interfaces/RndExpert";

export const RndExpertTableData: IRndExpert[] = [
  {
    id: 1,
    firstName: "Dave",
    lastName: "Seth",
    email: "dave.seth@gmail.com",
    phone: "+44 8500 287507",
    consultationFee: "£482.40",
    consultedUsers: 28,
    ratingStar: 3,
    status:true,
  },
  {
    id: 2,
    firstName: "Smith",
    lastName:"",
    email: "smith@gmail.com",
    phone: "+44 8500 287507",
    consultationFee: "£482.40",
    consultedUsers: 39,
    ratingStar: 4,
    status:false,
  },
  {
    id: 3,
    firstName: "Alexander",
    lastName:"",
    email: "alexandar@gmail.com",
    phone: "+44 8500 287507",
    consultationFee: "£482.40",
    consultedUsers: 10,
    ratingStar: 2,
    status:true,
  },
  {
    id: 4,
    firstName: "Charles",
    lastName:"",
    email: "charles@gmail.com",
    phone: "+44 8500 287507",
    consultationFee: "£482.40",
    consultedUsers: 20,
    ratingStar: 4,
    status:true,
  },
  {
    id: 5,
    firstName: "Ben",
    lastName: "John",
    email: "benjohn@gmail.com",
    phone: "+44 8500 287507",
    consultationFee: "£482.40",
    consultedUsers: 40,
    ratingStar: 5,
    status:true,
  },
  {
    id: 6,
    firstName: "Michel",
    lastName:"",
    email: "michel@gmail.com",
    phone: "+44 8500 287507",
    consultationFee: "£482.40",
    consultedUsers: 35,
    ratingStar: 2,
    status:true,
  },
  {
    id: 7,
    firstName: "David",
    lastName:"",
    email: "david@gmail.com",
    phone: "+44 8500 287507",
    consultationFee: "£482.40",
    consultedUsers: 22,
    ratingStar: 5,
    status:true,
  },
  {
    id: 8,
    firstName: "Alex",
    lastName:"",
    email: "alex@gmail.com",
    phone: "+44 8500 287507",
    consultationFee: "£482.40",
    consultedUsers: 15,
    ratingStar: 3,
    status:true,
  },
];
