export const ApiInventoryList = [
  {
    id: 1,
    apiName: "QuickBooks ",
    apiLink: "https://quickbooks.intuit.com/eu/oa/online",
    hitsPerMin: "20",
    averageResponseTime: "17:00:25m",
  },
  {
    id: 2,
    apiName: "Contract Book",
    apiLink: "https://contractbook.com/",
    hitsPerMin: "15",
    averageResponseTime: "18:00:25m",
  },
  {
    id: 3,
    apiName: "Amazon SNS",
    apiLink: "https://aws.amazon.com/free....",
    hitsPerMin: "11",
    averageResponseTime: "21:00:25m",
  },
  {
    id: 4,
    apiName: "Veriff",
    apiLink: "https://www.veriff.com/",
    hitsPerMin: "25",
    averageResponseTime: "24:00:25m",
  },
  {
    id: 5,
    apiName: "Stripe",
    apiLink: "https://stripe.com/nl",
    hitsPerMin: "17",
    averageResponseTime: "12:00:25m",
  },
  {
    id: 6,
    apiName: "Geolocation",
    apiLink: "https://www.google.com/maps/d/...",
    hitsPerMin: "10",
    averageResponseTime: "08:00:29m",
  },
  {
    id: 7,
    apiName: "Amazon Texract",
    apiLink: "https://aws.amazon.com/free....",
    hitsPerMin: "21",
    averageResponseTime: "09:00:25m",
  },
  {
    id: 8,
    apiName: "Amazon ENS",
    apiLink: "https://aws.amazon.com/free....",
    hitsPerMin: "26",
    averageResponseTime: "10:00:50m",
  },
  {
    id: 9,
    apiName: "QuickBooks ",
    apiLink: "https://quickbooks.intuit.com/eu/oa/online",
    hitsPerMin: "20",
    averageResponseTime: "17:00:25m",
  },
  {
    id: 10,
    apiName: "Contract Book",
    apiLink: "https://contractbook.com/",
    hitsPerMin: "15",
    averageResponseTime: "18:00:25m",
  },
  {
    id: 11,
    apiName: "Amazon SNS",
    apiLink: "https://aws.amazon.com/free....",
    hitsPerMin: "11",
    averageResponseTime: "21:00:25m",
  },
  {
    id: 12,
    apiName: "Veriff",
    apiLink: "https://www.veriff.com/",
    hitsPerMin: "25",
    averageResponseTime: "24:00:25m",
  },
  {
    id: 13,
    apiName: "Stripe",
    apiLink: "https://stripe.com/nl",
    hitsPerMin: "17",
    averageResponseTime: "12:00:25m",
  },
  {
    id: 14,
    apiName: "Geolocation",
    apiLink: "https://www.google.com/maps/d/...",
    hitsPerMin: "10",
    averageResponseTime: "08:00:29m",
  },
  {
    id: 15,
    apiName: "Amazon Texract",
    apiLink: "https://aws.amazon.com/free....",
    hitsPerMin: "21",
    averageResponseTime: "09:00:25m",
  },
  {
    id: 16,
    apiName: "Amazon ENS",
    apiLink: "https://aws.amazon.com/free....",
    hitsPerMin: "26",
    averageResponseTime: "10:00:50m",
  },
];
