import { deleteCollaborator } from "../redux/collaborator/collaborators-api";

export const endpoints = {
  user: `/users`,
  signin: `/users/login`,
  createCollaborator: `/users/create-collaborator`,
  collaborator: `/collaborators/list`,
  veriffSession: `/users/veriff-session`,
  verificationStatus: `/users/verification-status`,
  userConfirm: `/users/confirm`,
  resendCode: `users/resend-code`,
  company: `/company`,
  calendarEvents: `/calendar/events`,
  clients: `/clients`,
  clientSearch: `/clients/search`,
  question: `/questionaires`,
  claims: `/claims`,
  questionContact: `/questionaires/contact`,
  changeEmail: `/users/change-email`,
  changeEmailConfirm: `/users/change-email-confirm`,
  cardSetupIntent: `/users/card-setup-intent`,
  UserCardList: `/users/cards-list`,
  duplicateClaim: `/claims/duplicate`,
  userDeleteCard: `/users/delete-card`,
  rememberMe: `users/refresh-token`,
  logout: `users/logout`,
  reminders: `/reminders`,
  calendar:`/calendar`,
  calendarAvailability:`/calendar/availability`,
  collections:`/collections`,
  collaboratorChangeCostStatus:`collaborators/change-cost-status`,
  deleteCollaborator:`collaborators/delete-account`,
  calendarMeeting: `/calendar/meeting`,
  dashboardCount: `/dashboard/generic/count`,
  profileUpdate: `/users/update-profile`,
  profileImageUpdate: `/users/update-picture`,
  invoiceUserList: `/users/invoice-list`,
  userProfile:`users/profile`,
  rndExpertList:`/users/list-rndexperts`,
  createSubIndividual:'/users/create-subindividual',
  getSubindivisual:'/users/list-subindividual',
  updateSubindivisual:'/users/update-subindividual',
  getAuditLogs:'/dashboard/logs',
  getNewsletter:'/newsletters',
  getSubscribedUser:'/newsletters/users',
  createSubscribedUser:'/newsletters/users',

  recentActivities:`/dashboard/recent-activities`,
};
