export const claimsTabledata = [
  {
    id: 1,
    name: "Capso Therapeutics",
    username: "Arthur Lewin",
    claimPeriod: "01 Jan, 2020 - 31 Dec, 2020",
    progress: "1",
    status: "inreview",
    IsArchive: false,
    totalClaims: 1,
  },
  {
    id: 2,
    name: "Visions Technology",
    username: "Martin Luther",
    claimPeriod: "Not yet specified",
    progress: "1",
    status: "inprogress",
    IsArchive: false,
    totalClaims: 1,
  },
  {
    id: 3,
    name: "Urban Decay",
    username: "Joseph Arden",
    claimPeriod: "01 Jan, 2020 - 31 Dec, 2020",
    progress: "1",
    status: "readyToDownload",
    IsArchive: false,
    totalClaims: 1,
  },
  {
    id: 4,
    name: "Workers Limited",
    username: "Ben John",
    claimPeriod: "Not yet specified",
    progress: "1",
    status: "purchased",
    IsArchive: false,
    totalClaims: 1,
  },

  {
    id: 5,
    name: "Two News Limited",
    username: "Mark Twain",
    claimPeriod: "Not yet specified",
    progress: "1",
    status: "inprogress",
    IsArchive: false,
    totalClaims: 0,
  },
  {
    id: 6,
    name: "Spiffy Values",
    username: "James Anderson",
    claimPeriod: "Not yet specified",
    progress: "1",
    status: "ineligible",
    IsArchive: false,
    totalClaims: 1,
  },
  {
    id: 7,
    name: "Wanda Vision",
    username: "Alex Hales",
    claimPeriod: "Not yet specified",
    progress: "1",
    status: "inprogress",
    IsArchive: false,
    totalClaims: 1,
  },
  {
    id: 8,
    name: "Trend Technology",
    username: "Michael Anderson",
    claimPeriod: "Not yet specified",
    progress: "1",
    status: "inprogress",
    IsArchive: false,
    totalClaims: 0,
  },
  {
    id: 9,
    name: "Spiffy Values",
    username: "James Anderson",
    claimPeriod: "Not yet specified",
    progress: "1",
    status: "ineligible",
    IsArchive: false,
    totalClaims: 4,
  },
  {
    id: 10,
    name: "Wanda Vision",
    username: "Alex Hales",
    claimPeriod: "Not yet specified",
    progress: "1",
    status: "readyToDownload",
    IsArchive: false,
    totalClaims: 0,
  },
  {
    id: 11,
    name: "Trend Technology",
    username: "Michael Anderson",
    claimPeriod: "Not yet specified",
    progress: "1",
    status: "inprogress",
    IsArchive: false,
    totalClaims: 3,
  },
  {
    id: 12,
    name: "Trend Technology",
    username: "Michael Anderson",
    claimPeriod: "Not yet specified",
    progress: "1",
    status: "inreview",
    IsArchive: true,
    totalClaims: 1,
  },
];
