export const clientTabledata= [
  {
    id: 1,
    name: "Capso Therapeutics",
    phoneNumber: 111122333,
    userName: "Arthur Lewin",
    claimsInProgress: 5,
    claimsInReview: 1,
    claimsReadyToDownload: 1,
    purchasedClaims: 1,
    ineligibleClaims: 1,
  },
  {
    id: 2,
    name: "Visions Technology",
    phoneNumber: 111122333,
    userName: "Martin Luther",
    claimsInProgress: 5,
    claimsInReview: 1,
    claimsReadyToDownload: 1,
    purchasedClaims: 1,
    ineligibleClaims: 1,
  },
  {
    id: 3,
    name: "Urban Decay",
    phoneNumber: 111122333,
    userName: "Joseph Arden",
    claimsInProgress: 5,
    claimsInReview: 1,
    claimsReadyToDownload: 1,
    purchasedClaims: 1,
    ineligibleClaims: 1,
  },
  {
    id: 4,
    name: "Workers Limited",
    phoneNumber: 111122333,
    userName: "Ben John",
    claimsInProgress: 5,
    claimsInReview: 1,
    claimsReadyToDownload: 1,
    purchasedClaims: 1,
    ineligibleClaims: 1,
  },
  {
    id: 5,
    name: "Two News Limited",
    phoneNumber: 111122333,
    userName: "Mark Twain",
    claimsInProgress: 5,
    claimsInReview: 1,
    claimsReadyToDownload: 1,
    purchasedClaims: 1,
    ineligibleClaims: 1,
  },
  {
    id: 6,
    name: "Spiffy Values",
    phoneNumber: 111122333,
    userName: "James Anderson",
    claimsInProgress: 5,
    claimsInReview: 1,
    claimsReadyToDownload: 1,
    purchasedClaims: 1,
    ineligibleClaims: 1,
  },
  {
    id: 7,
    name: "Wanda Vision",
    phoneNumber: 111122333,
    userName: "Alex Hales",
    claimsInProgress: 5,
    claimsInReview: 1,
    claimsReadyToDownload: 1,
    purchasedClaims: 1,
    ineligibleClaims: 1,
  },
  {
    id: 8,
    name: "Trend Technology",
    phoneNumber: 111122333,
    userName: "Michael Anderson",
    claimsInProgress: 5,
    claimsInReview: 1,
    claimsReadyToDownload: 1,
    purchasedClaims: 1,
    ineligibleClaims: 1,
  },
  {
    id: 9,
    name: "Capso Therapeutics",
    phoneNumber: 111122333,
    userName: "Arthur Lewin",
    claimsInProgress: 5,
    claimsInReview: 1,
    claimsReadyToDownload: 1,
    purchasedClaims: 1,
    ineligibleClaims: 1,
  },
  {
    id: 10,
    name: "Visions Technology",
    phoneNumber: 111122333,
    userName: "Martin Luther",
    claimsInProgress: 5,
    claimsInReview: 1,
    claimsReadyToDownload: 1,
    purchasedClaims: 1,
    ineligibleClaims: 1,
  },
  {
    id: 11,
    name: "Urban Decay",
    phoneNumber: 111122333,
    userName: "Joseph Arden",
    claimsInProgress: 5,
    claimsInReview: 1,
    claimsReadyToDownload: 1,
    purchasedClaims: 1,
    ineligibleClaims: 1,
  },
  {
    id: 12,
    name: "Workers Limited",
    phoneNumber: 111122333,
    userName: "Ben John",
    claimsInProgress: 5,
    claimsInReview: 1,
    claimsReadyToDownload: 1,
    purchasedClaims: 1,
    ineligibleClaims: 1,
  },
  {
    id: 13,
    name: "Two News Limited",
    phoneNumber: 111122333,
    userName: "Mark Twain",
    claimsInProgress: 5,
    claimsInReview: 1,
    claimsReadyToDownload: 1,
    purchasedClaims: 1,
    ineligibleClaims: 1,
  },
];
