export const collaboratorsTabledata = [
    {
      "id": 1,
      "name": "David Williams",
      "email": "david.williams@gmail.com",
      "claims": ["Capso Therapeutics"],
      "invited": true,
      "joined": true,
      "submited": true,
      "costQuestions": true,
    },
    {
      "id": 2,
      "name": "Mark Cooper",
      "email": "mark.cooper@gmail.com",
      "claims": ["Visions Technology"],
      "invited": false,
      "joined": false,
      "submited": false,
      "costQuestions": false,
    },
    {
      "id": 3,
      "name": "David Williams",
      "email": "david.williams@gmail.com",
      "claims": ["Urban Decay"],
      "invited": false,
      "joined": false,
      "submited": false,
      "costQuestions": false,
    },
    {
      "id": 4,
      "name": "Mark Cooper",
      "email": "mark.cooper@gmail.com",
      "claims": ["Workers Limited"],
      "invited": false,
      "joined": false,
      "submited": false,
      "costQuestions": false,
    },
    {
      "id": 5,
      "name": "David Williams",
      "email": "david.williams@gmail.com",
      "claims": ["Capso Therapeutics"],
      "invited": true,
      "joined": true,
      "submited": true,
      "costQuestions": true,
    },
    {
      "id": 6,
      "name": "Mark Cooper",
      "email": "mark.cooper@gmail.com",
      "claims": ["Visions Technology"],
      "invited": false,
      "joined": false,
      "submited": false,
      "costQuestions": false,
    },
    {
      "id": 7,
      "name": "David Williams",
      "email": "david.williams@gmail.com",
      "claims": ["Urban Decay"],
      "invited": false,
      "joined": false,
      "submited": false,
      "costQuestions": false,
    },
    {
      "id": 8,
      "name": "Mark Cooper",
      "email": "mark.cooper@gmail.com",
      "claims": ["Workers Limited"],
      "invited": false,
      "joined": false,
      "submited": false,
      "costQuestions": false,
    },
    {
      "id": 9,
      "name": "David Williams",
      "email": "david.williams@gmail.com",
      "claims": ["Capso Therapeutics"],
      "invited": true,
      "joined": true,
      "submited": true,
      "costQuestions": true,
    },
    {
      "id": 10,
      "name": "Mark Cooper",
      "email": "mark.cooper@gmail.com",
      "claims": ["Visions Technology"],
      "invited": false,
      "joined": false,
      "submited": false,
      "costQuestions": false,
    },
    {
      "id": 11,
      "name": "David Williams",
      "email": "david.williams@gmail.com",
      "claims": ["Urban Decay"],
      "invited": false,
      "joined": false,
      "submited": false,
      "costQuestions": false,
    },
    {
      "id": 12,
      "name": "Mark Cooper",
      "email": "mark.cooper@gmail.com",
      "claims": ["Workers Limited"],
      "invited": false,
      "joined": false,
      "submited": false,
      "costQuestions": false,
    },
  ]
