import { IManageUsersTable } from "../interfaces/manageUersInterface";

export const managerUsersTabledata : IManageUsersTable[]  = [
  {
    id: 1,
    manageUser: "David Williams",
    userType: "Individual",
    email: "DavidW@gmail.com",
    noOfClients: 3,
    phoneNumber: "+44 4356 768923",
    manageUsersStatus: true,
  },
  {
    id: 2,
    manageUser: "Mark Cooper",
    userType: "Company",
    email: "MarkC@gmail.com",
    noOfClients: 2,
    phoneNumber: "+44 4356 768923",
    manageUsersStatus: true,
  },
  {
    id: 3,
    manageUser: "David Williams",
    userType: "Individual",
    email: "DavidW@gmail.com",
    noOfClients: 3,
    phoneNumber: "+44 4356 768923",
    manageUsersStatus: false,
  },
  {
    id: 4,
    manageUser: "Mark Cooper",
    userType: "Individual",
    email: "MarkC@gmail.com",
    noOfClients: 1,
    phoneNumber: "+44 4356 768923",
    manageUsersStatus: true,
  },
  {
    id: 5,
    manageUser: "David Williams",
    userType: "Company",
    email: "Robert@gmail.com",
    noOfClients: 2,
    phoneNumber: "+44 4356 768923",
    manageUsersStatus: false,
  },
  {
    id: 6,
    manageUser: "Andrew Simmons",
    userType: "Company",
    email: "William@gmail.com",
    noOfClients: 0,
    phoneNumber: "+44 4356 768923",
    manageUsersStatus: true,
  },
  {
    id: 7,
    manageUser: "Brad Shaw",
    userType: "Company",
    email: "Ronaldo@gmail.com",
    noOfClients: 1,
    phoneNumber: "+44 4356 768923",
    manageUsersStatus: false,
  },
  {
    id: 8,
    manageUser: "Andrew Simmons",
    userType: "Company",
    email: "David@gmail.com",
    noOfClients: 1,
    phoneNumber: "+44 4356 768923",
    manageUsersStatus: false,
  },
  {
    id: 9,
    manageUser: "David Williams",
    userType: "Individual",
    email: "DavidW@gmail.com",
    noOfClients: 3,
    phoneNumber: "+44 4356 768923",
    manageUsersStatus: true,
  },
  {
    id: 10,
    manageUser: "David Williams",
    userType: "Individual",
    email: "DavidW@gmail.com",
    noOfClients: 3,
    phoneNumber: "+44 4356 768923",
    manageUsersStatus: true,
  },
  {
    id: 11,
    manageUser: "David Williams",
    userType: "Individual",
    email: "DavidW@gmail.com",
    noOfClients: 3,
    phoneNumber: "+44 4356 768923",
    manageUsersStatus: true,
  },
  {
    id: 12,
    manageUser: "David Williams",
    userType: "Individual",
    email: "DavidW@gmail.com",
    noOfClients: 3,
    phoneNumber: "+44 4356 768923",
    manageUsersStatus: true,
  },
];
