
import {
  aOne,
  aTwo,
  aThree,
  aFour,
  aFive,
  aSix,
  aSeven,
  aEight,
} from "../../assets/export";

export const subscribedUsersTabledata = [
    {
      "id": 1,
      "avatar": aOne,
      "name": "David Williams",
      "email": "david.williams@gmail.com",
      "subscriptionDate": "01-15-2021",
      "status": true,
      "sendTo": false,
    },
    {
      "id": 2,
      "avatar": aTwo,
      "name": "Mark Cooper",
      "email": "mark.cooper@gmail.com",
      "subscriptionDate": "08-08-2018",
      "status": false,
      "sendTo": false,
    },
    {
      "id": 3,
      "avatar": aThree,
      "name": "Mike Scofield",
      "email": "scofield.michael@gmail.com",
      "subscriptionDate": "08-08-2018",
      "status": true,
      "sendTo": false,
    },
    {
      "id": 4,
      "avatar": aFour,
      "name": "Neng Kinasih",
      "email": "kinasih.neng@gmail.com",
      "subscriptionDate": "08-08-2018",
      "status": true,
      "sendTo": false,
    },
    {
      "id": 5,
      "avatar": aFive,
      "name": "Sisilia Sinta",
      "email": "sintasisilia99@gmail.com",
      "subscriptionDate": "08-08-2018",
      "status": true,
      "sendTo": false,
    },
    {
      "id": 6,
      "avatar": aSix,
      "name": "Andrew Simmons",
      "email": "sim.andrew187@gmail.com",
      "subscriptionDate": "08-08-2018",
      "status": true,
      "sendTo": false,
    },
    {
      "id": 7,
      "avatar": aSeven,
      "name": "Brad Shaw",
      "email": "brad.shaw@gmail.com",
      "subscriptionDate": "08-08-2018",
      "status": true,
      "sendTo": false,
    },
    {
      "id": 8,
      "avatar": aEight,
      "name": "Jeon Mido",
      "email": "jeon.mido@gmail.com",
      "subscriptionDate": "08-08-2018",
      "status": true,
      "sendTo": false,
    },
    {
      "id": 9,
      "avatar": aEight,
      "name": "Mido Jeon ",
      "email": "Midojeon.mido@gmail.com",
      "subscriptionDate": "08-04-2022",
      "status": true,
      "sendTo": false,
    },
    
    
  ]
